# Generated by Django 3.2 on 2022-09-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_data_migration'),
    ]

    operations = [
    ]
